# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies including dev for tsx
COPY package.json pnpm-lock.yaml ./
RUN npm install

# Copy entire project
COPY . .

# Expose no ports needed for stdio transport

# Default command to start the MCP server in ESM via tsx
CMD ["npx", "tsx", "src/mcp-server.ts"]
